# This is a basic workflow to help you get started with Actions

name: FetchStaticSecretsExample

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "fetch_secrets"
  fetch_secrets:
    # The type of runner that the job will run on
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fetch dynamic secrets from Akeyless
        uses: akeyless-community/akeyless-github-action@v1.0.1
        id: fetch-secrets
        with:
          access-id: '${{secrets.ACCESS_ID}}'
          access-type: jwt
          export-secrets-to-outputs: true
          export-secrets-to-environment: true
          dynamic-secrets: |
            - name: "jenkins/postgres"
              output-name: "postgres_dynamic_secret"
          api-url: "https://csm.thalescryptolabs.com/akeyless-api/v2/"

      - name: Export Secrets to Environment
        run: |
          echo '${{steps.fetch-dynamic-secrets.outputs.postgres_dynamic_secret}}' | jq -r 'to_entries|map("POSTGRES_\(.key|ascii_upcase)=\(.value|tostring)")|.[]' >> $GITHUB_ENV

      - name: Verify vars
        run: |
          echo "host:${{env.POSTGRES_HOST}}" >> secrets.txt
          echo "port:${{env.POSTGRES_PORT}}" >> secrets.txt
          echo "username:${{env.POSTGRES_USER}}" >> secrets.txt
          echo "password:${{env.POSTGRES_PASSWORD}}" >> secrets.txt
          echo "db_name:${{env.POSTGRES_DB_NAME}}" >> secrets.txt
          echo "ttl_in_minutes:${{env.POSTGRES_TTL_IN_MINUTES}}" >> secrets.txt
        
        
