# This is a basic workflow to help you get started with Actions

name: FetchStaticSecretsExample

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "fetch_secrets"
  fetch_secrets:
    # The type of runner that the job will run on
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fetch static secrets from Akeyless
        uses: akeyless-community/akeyless-github-action@v1.0.1
        id: fetch-secrets
        with:
          access-id: '${{secrets.ACCESS_ID}}'
          access-type: jwt
          export-secrets-to-outputs: true
          export-secrets-to-environment: true
          static-secrets: |
            - name: "github_actions/testsecret"
              output-name: "my_first_secret"
          api-url: "https://csm.thalescryptolabs.com/akeyless-api/v2/"

      - name: Use Akeyless secret (environment variable)
        env:
          SECRET: ${{env.my_first_secret}}
        run: |
          # Use the secret securely within this step
          echo "Doing something with $SECRET"

      - name: Use Akeyless secret (step output)
        run: |
          # Use the secret securely within this step
          echo "Doing something with ${{steps.fetch-secrets.outputs.my_first_secret}}"
